# -*- coding: utf-8 -*-
"""correlation_task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBjgjsEeTe-Y_7HcEmbb5ZxoaSatc82Z
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# STEP 1
# Values extracted strictly from the bottom-right tooltips
x_values = [
    -8.50, -8.00, -6.00, -3.00, -1.70,
     1.20,  3.50,  5.00,  7.00,  9.00
]

y_values = [
     7.00,  5.50,  3.50,  4.00,  2.00,
     0.90, -2.50, -3.00, -4.00, -5.00
]

# --- STEP 2: Calculate Pearson's Correlation Coefficient ---
correlation, _ = pearsonr(x_values, y_values)
print(f"Number of Data Points: {len(x_values)}")
print(f"Pearson's Correlation Coefficient (r): {correlation:.4f}")

# --- STEP 3: Generate Visualization ---
plt.figure(figsize=(10, 6))
plt.scatter(x_values, y_values, color='#87CEEB', edgecolors='b', s=100, zorder=3, label='Data Points')

# Trendline
m, b = np.polyfit(x_values, y_values, 1)
plt.plot(x_values, m*np.array(x_values) + b, color='red', linestyle='--', label=f'Trendline')

plt.title(f"Correlation Analysis\nPearson r: {correlation:.4f}")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.axhline(0, color='black', linewidth=0.8)
plt.axvline(0, color='black', linewidth=0.8)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6, zorder=0)

# Saving
plt.savefig("correlation_graph.png")
print("Graph saved as 'correlation_graph.png'")
plt.show()